// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",           // Location of Prisma schema file
  migrations: {
    path: "prisma/migrations",              // Directory for migration files
  },
  datasource: {
    url: process.env["DATABASE_DEV_URL"],   // Database connection string from environment variables
  },
});